# =========================
# prod profile exclusive setting
# =========================

spring.config.activate.on-profile=prod

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.org.springframework=INFO
logging.level.com.resumerefiner=INFO
logging.level.org.hibernate.SQL=INFO
