# =========================
# local profile exclusive Setting
# =========================

spring.config.activate.on-profile=local

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.resumerefiner=DEBUG

# CORS can be set here if needed

# Local Storage Dir (Under Project Root)
app.storage.local.root-dir=${APP_STORAGE_LOCAL_ROOT_DIR:./.local-storage}

# base url For Local File Access ( /api Also Possible if frontend Accesses through Backend)
app.storage.local.public-base-url=${APP_STORAGE_LOCAL_PUBLIC_BASE_URL:http://localhost:8080}