# =========================
# prod profile exclusive setting
# =========================

spring.config.activate.on-profile=prod

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.org.springframework=INFO
logging.level.com.resumerefiner=INFO
logging.level.org.hibernate.SQL=INFO

app.storage.s3.bucket=${APP_S3_BUCKET}
app.storage.s3.region=${APP_S3_REGION:ap-northeast-2}
app.storage.s3.public-base-url=${APP_S3_PUBLIC_BASE_URL}
