spring.config.activate.on-profile=local

app.web.base-url=http://localhost:3000
app.web.oauth-success-path=/oauth/success
app.web.oauth-failure-path=/oauth/failure

# CORS Allowed(Local)
app.web.allowed-origin-patterns[0]=http://localhost:3000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.resumerefiner=DEBUG

# Local Storage
app.storage.local.root-dir=${APP_STORAGE_LOCAL_ROOT_DIR:./.local-storage}
app.storage.local.public-base-url=${APP_STORAGE_LOCAL_PUBLIC_BASE_URL:http://localhost:8080}

# Sessions/Cookie (local)
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
